services:
  - type: web
    name: sharik_bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false        # you'll paste this manually in Render UI
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: sharik_bot
          property: host   # Render fills this in automatically
